// 100% Authentic RG Motors Stock from Official PDF Inventory
export interface VehicleSpin {
  count: number;
  pattern?: string;
  ext?: string;
}

export interface Vehicle {
  slug: string;
  plate?: string;
  brand: string;
  model: string;
  version: string;
  year: number;
  price: number;
  listPrice?: number;
  km: number;
  fuel: string;
  transmission: string;
  bodyType: string;
  location: string;
  image: string;
  gallery?: string[];
  spin?: VehicleSpin;
  engine: string;
  power: string;
  traction: string;
  doors: number;
  owners: number;
  featured?: boolean;
  status?: "Disponible" | "En reserva" | "Vendido" | "Borrador" | "En preparación";
  hasRealPhotos?: boolean;
  supplier?: string;
  techReview?: string;
  circPermit?: string;
  highlights?: string[];
}

export const initialVehicles: Vehicle[] = [
  {
    "slug": "ford-raptor-f150-2025-tskl58",
    "plate": "TSKL 58",
    "brand": "Ford",
    "model": "RAPTOR F150",
    "version": "RAPTOR F150 · Negro",
    "year": 2025,
    "price": 69990000,
    "km": 10000,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RUDELL",
    "techReview": "EN PODER DE DON RUDY",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "3.5L V6 EcoBoost Twin-Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "ford-raptor-f150-2022-rxzt82",
    "plate": "RXZT 82",
    "brand": "Ford",
    "model": "RAPTOR F150",
    "version": "RAPTOR F150 · Blanco",
    "year": 2022,
    "price": 59990000,
    "km": 82638,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RUDY",
    "techReview": "EN PODER DE DON RUDY",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "3.5L V6 EcoBoost Twin-Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "ford-raptor-f150-2020-lrjy32",
    "plate": "LRJY 32",
    "brand": "Ford",
    "model": "RAPTOR F150",
    "version": "RAPTOR F150 · Rojo",
    "year": 2020,
    "price": 39990000,
    "km": 136279,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RUDY",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "3.5L V6 EcoBoost Twin-Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "subaru-wrx-sti-4x4-2-5-2022-rkrg58",
    "plate": "RKRG 58",
    "brand": "Subaru",
    "model": "WRX STI 4X4 2.5",
    "version": "WRX STI 4X4 2.5 · Azul",
    "year": 2022,
    "price": 39990000,
    "listPrice": 40990000,
    "km": 0,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Sedán",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RG Motors",
    "techReview": "Al día",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "2.5L Turbo",
    "power": "300 HP",
    "traction": "4x4",
    "doors": 2,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "hino-xzu-617-dc-2023-sklf13",
    "plate": "SKLF 13",
    "brand": "Hino",
    "model": "XZU 617 DC",
    "version": "XZU 617 DC · Blanco",
    "year": 2023,
    "price": 25990000,
    "listPrice": 26990000,
    "km": 103000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camión",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "abril 2026",
    "circPermit": "SEPTIEMBRE",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "toyota-hilux-sr-4x4-2024-thsr65",
    "plate": "THSR 65",
    "brand": "Toyota",
    "model": "HILUX SR 4X4",
    "version": "HILUX SR 4X4 · Rojo",
    "year": 2024,
    "price": 24990000,
    "listPrice": 25990000,
    "km": 90386,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "AGOSTO",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "toyota-hilux-sr-4x4-2022-rwyr12",
    "plate": "RWYR 12",
    "brand": "Toyota",
    "model": "HILUX SR 4X4",
    "version": "HILUX SR 4X4 · Rojo",
    "year": 2022,
    "price": 22990000,
    "listPrice": 23990000,
    "km": 84000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RUDY",
    "techReview": "mayo 2026",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "toyota-hilux-4x4-2022-rzvk91",
    "plate": "RZVK 91",
    "brand": "Toyota",
    "model": "HILUX 4X4",
    "version": "HILUX 4X4 · Rojo",
    "year": 2022,
    "price": 17990000,
    "listPrice": 18990000,
    "km": 151000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "CHARRIOT",
    "techReview": "octubre 2026",
    "circPermit": "MARZO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "toyota-hilux-4x2-2023-swdv33",
    "plate": "SWDV 33",
    "brand": "Toyota",
    "model": "HILUX 4X2",
    "version": "HILUX 4X2 · Rojo",
    "year": 2023,
    "price": 15990000,
    "listPrice": 16990000,
    "km": 159378,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RUDY",
    "techReview": "junio 2027",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "toyota-new-hilux-4x2-2022-rpkd45",
    "plate": "RPKD 45",
    "brand": "Toyota",
    "model": "NEW HILUX 4X2",
    "version": "NEW HILUX 4X2 · Rojo",
    "year": 2022,
    "price": 14990000,
    "listPrice": 15990000,
    "km": 135704,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "AGOSTO",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "toyota-hilux-4x4-2022-rzvl18",
    "plate": "RZVL 18",
    "brand": "Toyota",
    "model": "HILUX 4X4",
    "version": "HILUX 4X4 · Rojo",
    "year": 2022,
    "price": 0,
    "km": 127576,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "CHARRIOT",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "status": "En preparación",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "toyota-hilux-sr-2023-swzj94",
    "plate": "SWZJ 94",
    "brand": "Toyota",
    "model": "HILUX SR",
    "version": "HILUX SR · Rojo",
    "year": 2023,
    "price": 0,
    "km": 0,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "CARDONAL",
    "techReview": "Al día",
    "circPermit": "Al día",
    "status": "En preparación",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "chevrolet-colorado-4x4-aut-2022-sfyb29",
    "plate": "SFYB 29",
    "brand": "Chevrolet",
    "model": "COLORADO 4X4 AUT.",
    "version": "COLORADO 4X4 AUT. · Blanco",
    "year": 2022,
    "price": 18990000,
    "listPrice": 19990000,
    "km": 111222,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RELSA RG MOTORS",
    "techReview": "enero 2027",
    "circPermit": "VENCIDO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "chevrolet-colorado-4x4-2022-rzsy35",
    "plate": "RZSY 35",
    "brand": "Chevrolet",
    "model": "COLORADO 4X4",
    "version": "COLORADO 4X4 · Blanco",
    "year": 2022,
    "price": 16990000,
    "listPrice": 17990000,
    "km": 144800,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION RG",
    "techReview": "AGOSTO",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "chevrolet-colorado-4x4-aut-2022-sfbl43",
    "plate": "SFBL 43",
    "brand": "Chevrolet",
    "model": "COLORADO 4X4 AUT.",
    "version": "COLORADO 4X4 AUT. · Blanco",
    "year": 2022,
    "price": 16990000,
    "listPrice": 17990000,
    "km": 149586,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "nissan-navara-xe-4x4-2021-rdhl11",
    "plate": "RDHL 11",
    "brand": "Nissan",
    "model": "NAVARA XE 4X4",
    "version": "NAVARA XE 4X4 · Blanco",
    "year": 2021,
    "price": 16990000,
    "listPrice": 17990000,
    "km": 79538,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RELSA RG MOTORS",
    "techReview": "ABRIL",
    "circPermit": "MARZO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "ford-ranger-4x4-2023-shyl53",
    "plate": "SHYL 53",
    "brand": "Ford",
    "model": "RANGER 4X4",
    "version": "RANGER 4X4 · Rojo",
    "year": 2023,
    "price": 15990000,
    "listPrice": 16990000,
    "km": 104628,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "JUNIO",
    "circPermit": "MARZO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "nissan-navara-4x2-2023-sjtd29",
    "plate": "SJTD 29",
    "brand": "Nissan",
    "model": "NAVARA 4X2",
    "version": "NAVARA 4X2 · Gris",
    "year": 2023,
    "price": 15990000,
    "listPrice": 17990000,
    "km": 80000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Salgado",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RUDY",
    "techReview": "ENERO",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "nissan-navara-xe-4x2-2024-tcgb98",
    "plate": "TCGB 98",
    "brand": "Nissan",
    "model": "NAVARA XE 4X2",
    "version": "NAVARA XE 4X2 · Rojo",
    "year": 2024,
    "price": 15990000,
    "listPrice": 17990000,
    "km": 125518,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "MAYO",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "nissan-navara-4x2-2024-tcpt20",
    "plate": "TCPT 20",
    "brand": "Nissan",
    "model": "NAVARA 4X2",
    "version": "NAVARA 4X2 · Rojo",
    "year": 2024,
    "price": 15990000,
    "listPrice": 17990000,
    "km": 51714,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RUDY",
    "techReview": "febrero 2028",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "chevrolet-colorado-4x4-aut-2022-sdjt43",
    "plate": "SDJT 43",
    "brand": "Chevrolet",
    "model": "COLORADO 4X4 AUT.",
    "version": "COLORADO 4X4 AUT. · Blanco",
    "year": 2022,
    "price": 15990000,
    "listPrice": 16990000,
    "km": 177865,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mitsubishi-katana-4x2-2024-thzf75",
    "plate": "THZF 75",
    "brand": "Mitsubishi",
    "model": "KATANA 4X2",
    "version": "KATANA 4X2 · Rojo",
    "year": 2024,
    "price": 14990000,
    "listPrice": 15990000,
    "km": 65000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "agosto 2026",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "volkswagen-amarok-4x4-mt-2022-rrkb78",
    "plate": "RRKB 78",
    "brand": "Volkswagen",
    "model": "AMAROK 4X4 MT",
    "version": "AMAROK 4X4 MT · Blanco",
    "year": 2022,
    "price": 14990000,
    "listPrice": 15990000,
    "km": 207000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "noviembre 2026",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "hyundai-porter-ii-2022-rpsh45",
    "plate": "RPSH 45",
    "brand": "Hyundai",
    "model": "PORTER II",
    "version": "PORTER II · Blanco",
    "year": 2022,
    "price": 14990000,
    "listPrice": 15990000,
    "km": 110000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camión",
    "location": "Puerto Montt · Sucursal Salgado",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION RG",
    "techReview": "AGOSTO",
    "circPermit": "AGOSTO",
    "status": "En preparación",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mitsubishi-new-katana-4x2-2023-srcp17",
    "plate": "SRCP 17",
    "brand": "Mitsubishi",
    "model": "NEW KATANA 4X2",
    "version": "NEW KATANA 4X2 · Rojo",
    "year": 2023,
    "price": 13990000,
    "listPrice": 15490000,
    "km": 75000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "octubre 2027",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mitsubishi-katana-work-4x2-2022-rggz96",
    "plate": "RGGZ 96",
    "brand": "Mitsubishi",
    "model": "KATANA WORK 4X2",
    "version": "KATANA WORK 4X2 · Blanco",
    "year": 2022,
    "price": 13990000,
    "listPrice": 14990000,
    "km": 148386,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "CONSIGNADO",
    "techReview": "SEPTIEMBRE",
    "circPermit": "MARZO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "chevrolet-dmax-4x4-2022-rpfs85",
    "plate": "RPFS 85",
    "brand": "Chevrolet",
    "model": "DMAX 4X4",
    "version": "DMAX 4X4 · Rojo",
    "year": 2022,
    "price": 13990000,
    "listPrice": 14990000,
    "km": 0,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "agosto 2026",
    "techReview": "AGOSTO",
    "circPermit": "CARDONAL",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x4-2020-lxcy98",
    "plate": "LXCY 98",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X4",
    "version": "L200 KATANA 4X4 · Rojo",
    "year": 2020,
    "price": 13490000,
    "listPrice": 14490000,
    "km": 156000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RQ RUDY CON IVA",
    "techReview": "NOVIEMBRE",
    "circPermit": "MARZO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x2-2022-rhkd26",
    "plate": "RHKD 26",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X2",
    "version": "L200 KATANA 4X2 · Rojo",
    "year": 2022,
    "price": 13490000,
    "listPrice": 14490000,
    "km": 139000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RQ RUDY CON IVA",
    "techReview": "SEPTIEMBRE",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "peugeot-partner-2025-tsxk53",
    "plate": "TSXK 53",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2025,
    "price": 12990000,
    "listPrice": 13990000,
    "km": 70000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RELSA RG MOTORS",
    "techReview": "JUNIO",
    "circPermit": "MARZO",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "maxus-t60-4x2-at-2023-stpz87",
    "plate": "STPZ 87",
    "brand": "Maxus",
    "model": "T60 4X2 AT",
    "version": "T60 4X2 AT · Gris",
    "year": 2023,
    "price": 12990000,
    "listPrice": 14990000,
    "km": 78000,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "octubre 2027",
    "circPermit": "MARZO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x4-2020-pgbv10",
    "plate": "PGBV 10",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X4",
    "version": "L200 KATANA 4X4 · Rojo",
    "year": 2020,
    "price": 12990000,
    "listPrice": 13990000,
    "km": 208401,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RQ RUDY CON IVA",
    "techReview": "FALTA DOCUME.",
    "circPermit": "FALTA DOCUME.",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "toyota-raize-4x2-1-2-2025-tsgl82",
    "plate": "TSGL 82",
    "brand": "Toyota",
    "model": "RAIZE 4X2 1.2",
    "version": "RAIZE 4X2 1.2 · Gris",
    "year": 2025,
    "price": 12490000,
    "listPrice": 13490000,
    "km": 16000,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RUDY",
    "techReview": "MAYO",
    "circPermit": "MARZO",
    "status": "Disponible",
    "engine": "1.2L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mitsubishi-l200-work-4x2-2021-pxsv97",
    "plate": "PXSV 97",
    "brand": "Mitsubishi",
    "model": "L200 WORK 4X2",
    "version": "L200 WORK 4X2 · Rojo",
    "year": 2021,
    "price": 12490000,
    "listPrice": 13490000,
    "km": 139113,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RQ RUDY CON IVA SIN REVISION/vence octubre",
    "techReview": "MARZO",
    "circPermit": "CARDONAL",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "ssangyong-musso-grand-4x2-2021-rdhb85",
    "plate": "RDHB 85",
    "brand": "SsangYong",
    "model": "MUSSO GRAND 4X2",
    "version": "MUSSO GRAND 4X2 · Gris",
    "year": 2021,
    "price": 11990000,
    "listPrice": 12990000,
    "km": 156000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RQ RUDY CON IVA",
    "techReview": "AGOSTO",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "ssangyong-musso-grand-2021-rdhb71",
    "plate": "RDHB 71",
    "brand": "SsangYong",
    "model": "MUSSO GRAND",
    "version": "MUSSO GRAND · Gris",
    "year": 2021,
    "price": 11990000,
    "listPrice": 12990000,
    "km": 161404,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Salgado",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RQ RUDY CON IVA",
    "techReview": "FALTA DOCUME.",
    "circPermit": "FALTA DOCUME.",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "maxus-t60-dx-4x4-2023-ssdt39",
    "plate": "SSDT 39",
    "brand": "Maxus",
    "model": "T60 DX 4X4",
    "version": "T60 DX 4X4 · Rojo",
    "year": 2023,
    "price": 10990000,
    "listPrice": 11990000,
    "km": 134000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "MITTA BANCO",
    "techReview": "ENERO",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "chevrolet-dmax-4x2-2020-lxbc60",
    "plate": "LXBC 60",
    "brand": "Chevrolet",
    "model": "DMAX 4X2",
    "version": "DMAX 4X2 · Rojo",
    "year": 2020,
    "price": 10990000,
    "listPrice": 11990000,
    "km": 195000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "MITTA BANCO",
    "techReview": "FEBRERO",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "peugeot-expert-2022-scdw37",
    "plate": "SCDW 37",
    "brand": "Peugeot",
    "model": "EXPERT",
    "version": "EXPERT · Blanco",
    "year": 2022,
    "price": 10990000,
    "listPrice": 11990000,
    "km": 236400,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "SEPTIEMBRE",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "maxus-t60-4x4-glx-2022-sdds52",
    "plate": "SDDS 52",
    "brand": "Maxus",
    "model": "T60 4X4 GLX",
    "version": "T60 4X4 GLX · Blanco",
    "year": 2022,
    "price": 10990000,
    "listPrice": 11990000,
    "km": 190305,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "mayo 2027",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "peugeot-partner-1-6-2023-sfxy80",
    "plate": "SFXY 80",
    "brand": "Peugeot",
    "model": "PARTNER 1,6",
    "version": "PARTNER 1,6 · Blanco",
    "year": 2023,
    "price": 10490000,
    "listPrice": 11490000,
    "km": 119136,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "FEBRERO",
    "circPermit": "MARZO",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "peugeot-partner-2023-svfb26",
    "plate": "SVFB 26",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2023,
    "price": 10490000,
    "km": 89498,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "peugeot-partner-2022-svfd42",
    "plate": "SVFD 42",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2022,
    "price": 10490000,
    "listPrice": 11490000,
    "km": 80438,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "SALGADO",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "volkswagen-saveiro-dc-2023-sfrt83",
    "plate": "SFRT 83",
    "brand": "Volkswagen",
    "model": "SAVEIRO DC",
    "version": "SAVEIRO DC · Blanco",
    "year": 2023,
    "price": 9990000,
    "listPrice": 10990000,
    "km": 69000,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "JUNIO",
    "circPermit": "MARZO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "peugeot-partner-2023-ssdd57",
    "plate": "SSDD 57",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2023,
    "price": 9990000,
    "km": 152557,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "volkswagen-saveiro-dcab-2023-sfrx48",
    "plate": "SFRX 48",
    "brand": "Volkswagen",
    "model": "SAVEIRO DCAB",
    "version": "SAVEIRO DCAB · Blanco",
    "year": 2023,
    "price": 9990000,
    "listPrice": 10990000,
    "km": 59000,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "NOVIEMBRE",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "maxus-t60-4x2-2022-sfwd31",
    "plate": "SFWD 31",
    "brand": "Maxus",
    "model": "T60 4X2",
    "version": "T60 4X2 · Blanco",
    "year": 2022,
    "price": 9990000,
    "listPrice": 10990000,
    "km": 69379,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "MITTA BANCO",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mitsubishi-new-katana-crt-4x2-2019-kwrc91",
    "plate": "KWRC 91",
    "brand": "Mitsubishi",
    "model": "NEW KATANA CRT 4X2",
    "version": "NEW KATANA CRT 4X2 · Rojo",
    "year": 2019,
    "price": 9990000,
    "listPrice": 10990000,
    "km": 389144,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RUDY",
    "techReview": "abril 2027",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "chevrolet-tracker-1-2t-2022-ryyx50",
    "plate": "RYYX 50",
    "brand": "Chevrolet",
    "model": "TRACKER 1.2T",
    "version": "TRACKER 1.2T · Azul",
    "year": 2022,
    "price": 9990000,
    "listPrice": 10990000,
    "km": 49273,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "C.PODER",
    "techReview": "SALGADO",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "1.2L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "omoda-c5-1-5-aut-2025-vblv57",
    "plate": "VBLV 57",
    "brand": "Omoda",
    "model": "C5 1.5 AUT",
    "version": "C5 1.5 AUT · Gris",
    "year": 2025,
    "price": 9990000,
    "listPrice": 10990000,
    "km": 32000,
    "fuel": "Bencina",
    "transmission": "Automática",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "C.PODER",
    "techReview": "SALGADO",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "1.5L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "peugeot-partner-2022-scgv34",
    "plate": "SCGV 34",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2022,
    "price": 9490000,
    "listPrice": 10490000,
    "km": 108806,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "peugeot-partner-1-6-2022-rzdc35",
    "plate": "RZDC 35",
    "brand": "Peugeot",
    "model": "PARTNER 1,6",
    "version": "PARTNER 1,6 · Blanco",
    "year": 2022,
    "price": 9490000,
    "km": 0,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "agosto 2026",
    "techReview": "AGOSTO",
    "circPermit": "CARDONAL",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mercedes-benz-ml300-cdi-2011-ddlj95",
    "plate": "DDLJ 95",
    "brand": "Mercedes-Benz",
    "model": "ML300 CDI",
    "version": "ML300 CDI · Blanco",
    "year": 2011,
    "price": 9490000,
    "listPrice": 10490000,
    "km": 216000,
    "fuel": "Bencina",
    "transmission": "Automática",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "C.PODER",
    "techReview": "AGOSTO",
    "circPermit": "marzo 2027",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "peugeot-partner-2021-psjj97",
    "plate": "PSJJ 97",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2021,
    "price": 8990000,
    "listPrice": 10490000,
    "km": 104900,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "OCTUBRE",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "peugeot-partner-2021-pysy84",
    "plate": "PYSY 84",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2021,
    "price": 8990000,
    "listPrice": 10990000,
    "km": 122000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION RG",
    "techReview": "JULIO",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "peugeot-partner-1-6-2022-rlvr54",
    "plate": "RLVR 54",
    "brand": "Peugeot",
    "model": "PARTNER 1,6",
    "version": "PARTNER 1,6 · Blanco",
    "year": 2022,
    "price": 8990000,
    "listPrice": 9990000,
    "km": 159176,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION RG",
    "techReview": "julio 2026",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "peugeot-partner-2022-rlvr63",
    "plate": "RLVR 63",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2022,
    "price": 7990000,
    "listPrice": 8990000,
    "km": 246000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "junio 2027",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mg-3-hatch-back-2022-rygb56",
    "plate": "RYGB 56",
    "brand": "MG",
    "model": "3 HATCH BACK",
    "version": "3 HATCH BACK · Blanco",
    "year": 2022,
    "price": 7490000,
    "listPrice": 8490000,
    "km": 60900,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Hatchback",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RELSA RG MOTORS",
    "techReview": "SEPTIEMBRE",
    "circPermit": "marzo 2027",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "ram-v700-2021-ptfc69",
    "plate": "PTFC 69",
    "brand": "RAM",
    "model": "V700",
    "version": "V700 · Blanco",
    "year": 2021,
    "price": 6990000,
    "listPrice": 7990000,
    "km": 141000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION RG",
    "techReview": "enero 2027",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mg-zs-1-5-2022-rtzh73",
    "plate": "RTZH 73",
    "brand": "MG",
    "model": "ZS 1.5",
    "version": "ZS 1.5 · Rojo",
    "year": 2022,
    "price": 6990000,
    "listPrice": 8490000,
    "km": 106000,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Salgado",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "C.PODER",
    "techReview": "JUNIO",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "1.5L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "renault-duster-expression-1-6-2015-hbdz43",
    "plate": "HBDZ 43",
    "brand": "Renault",
    "model": "DUSTER EXPRESSION 1.6",
    "version": "DUSTER EXPRESSION 1.6 · Negro",
    "year": 2015,
    "price": 4990000,
    "listPrice": 5990000,
    "km": 122000,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "C.PODER",
    "techReview": "JUNIO",
    "circPermit": "MARZO",
    "status": "Disponible",
    "engine": "1.6L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "nissan-terrano-4x2-2012-dxtz99",
    "plate": "DXTZ 99",
    "brand": "Nissan",
    "model": "TERRANO 4X2",
    "version": "TERRANO 4X2 · Blanco",
    "year": 2012,
    "price": 4990000,
    "listPrice": 5990000,
    "km": 246800,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Salgado",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "C.PODER",
    "techReview": "enero 2027",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "nissan-navara-se-4x4-2022-rhyh38",
    "plate": "RHYH 38",
    "brand": "Nissan",
    "model": "NAVARA SE 4X4",
    "version": "NAVARA SE 4X4 · Rojo",
    "year": 2022,
    "price": 135598,
    "listPrice": 15990000,
    "km": 0,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RG Motors",
    "techReview": "Al día",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "peugeot-partner-1-6-2022-scgj41",
    "plate": "SCGJ 41",
    "brand": "Peugeot",
    "model": "PARTNER 1.6",
    "version": "PARTNER 1.6 · Blanco",
    "year": 2022,
    "price": 0,
    "km": 110030,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "ABRIL",
    "circPermit": "MARZO",
    "status": "En reserva",
    "engine": "1.6L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mitsubishi-katana-4x4-2023-sgvc26",
    "plate": "SGVC 26",
    "brand": "Mitsubishi",
    "model": "KATANA 4X4",
    "version": "KATANA 4X4 · Rojo",
    "year": 2023,
    "price": 0,
    "km": 231741,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "SEPTIEMBRE",
    "circPermit": "AGOSTO",
    "status": "En preparación",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x2-2021-rbfk40",
    "plate": "RBFK 40",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X2",
    "version": "L200 KATANA 4X2 · Rojo",
    "year": 2021,
    "price": 0,
    "km": 182825,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RQ RUDY CON IVA",
    "techReview": "febrero 2027",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "peugeot-partner-hdi-92-l1-1-6-2022-sbzc70",
    "plate": "SBZC 70",
    "brand": "Peugeot",
    "model": "PARTNER HDI 92 L1 1.6",
    "version": "PARTNER HDI 92 L1 1.6 · Blanco",
    "year": 2022,
    "price": 0,
    "km": 150104,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION RG",
    "techReview": "febrero 2027",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "1.6L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "volkswagen-saveiro-cd-1-6-2022-slgd85",
    "plate": "SLGD 85",
    "brand": "Volkswagen",
    "model": "SAVEIRO CD 1.6",
    "version": "SAVEIRO CD 1.6 · Blanco",
    "year": 2022,
    "price": 0,
    "km": 0,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "CARDONAL",
    "techReview": "Al día",
    "circPermit": "Al día",
    "status": "En preparación",
    "engine": "1.6L",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "chevrolet-spark-gt-lt-1-2-2021-pgft56",
    "plate": "PGFT 56",
    "brand": "Chevrolet",
    "model": "SPARK GT LT 1.2",
    "version": "SPARK GT LT 1.2 · Blanco",
    "year": 2021,
    "price": 0,
    "km": 58661,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Hatchback",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "C.PODER",
    "techReview": "SEPTIEMBRE",
    "circPermit": "AGOSTO",
    "status": "Disponible",
    "engine": "1.2L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x2-2024-thzg51",
    "plate": "THZG 51",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X2",
    "version": "L200 KATANA 4X2 · Rojo",
    "year": 2024,
    "price": 0,
    "km": 94407,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "status": "En preparación",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x4-2020-pgbv11",
    "plate": "PGBV 11",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X4",
    "version": "L200 KATANA 4X4 · Rojo",
    "year": 2020,
    "price": 0,
    "km": 129304,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RQ RUDY CON IVA",
    "techReview": "VENCIDO",
    "circPermit": "marzo 2027",
    "status": "En preparación",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mitsubishi-new-katana-4x4-2021-pkgf78",
    "plate": "PKGF 78",
    "brand": "Mitsubishi",
    "model": "NEW KATANA 4X4",
    "version": "NEW KATANA 4X4 · Rojo",
    "year": 2021,
    "price": 0,
    "km": 203454,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION RG",
    "techReview": "NOVIEMBRE",
    "circPermit": "AGOSTO",
    "status": "En preparación",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x2-2024-thlv62",
    "plate": "THLV 62",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X2",
    "version": "L200 KATANA 4X2 · Rojo",
    "year": 2024,
    "price": 0,
    "km": 69749,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION RG",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "status": "En preparación",
    "engine": "2.4L Turbo Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "jac-x200-2022-rzwv49",
    "plate": "RZWV 49",
    "brand": "JAC",
    "model": "X200",
    "version": "X200 · Blanco",
    "year": 2022,
    "price": 0,
    "km": 0,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camión",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "CARDONAL",
    "techReview": "Al día",
    "circPermit": "Al día",
    "status": "En preparación",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "mitsubishi-montero-sport-mt-2010-crbw65",
    "plate": "CRBW 65",
    "brand": "Mitsubishi",
    "model": "MONTERO SPORT MT",
    "version": "MONTERO SPORT MT · Blanco",
    "year": 2010,
    "price": 0,
    "km": 0,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "agosto 2026",
    "techReview": "AGOSTO",
    "circPermit": "CARDONAL",
    "status": "En preparación",
    "engine": "2.0L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "changan-alsvin-1-4-2021-plxf40",
    "plate": "PLXF 40",
    "brand": "Changan",
    "model": "ALSVIN 1.4",
    "version": "ALSVIN 1.4 · Gris",
    "year": 2021,
    "price": 0,
    "km": 155519,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Sedán",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "CONSIGNADO",
    "techReview": "CONSIGNADO DE CHARLIE EN SALGADO",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "1.4L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "peugeot-partner-l1-blue-hdi-100-1-5-2023-ssdy34",
    "plate": "SSDY 34",
    "brand": "Peugeot",
    "model": "PARTNER L1 BLUE HDI 100 1.5",
    "version": "PARTNER L1 BLUE HDI 100 1.5 · Blanco",
    "year": 2023,
    "price": 0,
    "km": 73000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Salgado",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "julio 2027",
    "circPermit": "AGOSTO",
    "status": "En preparación",
    "engine": "1.5L",
    "power": "140 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  },
  {
    "slug": "chevrolet-tahoe-lt-4wd-5-3-2017-jyfw75",
    "plate": "JYFW 75",
    "brand": "Chevrolet",
    "model": "TAHOE LT 4WD 5.3",
    "version": "TAHOE LT 4WD 5.3 · Celeste",
    "year": 2017,
    "price": 0,
    "km": 0,
    "fuel": "Bencina",
    "transmission": "Automática",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "supplier": "RG Motors",
    "techReview": "Al día",
    "circPermit": "Al día",
    "status": "Disponible",
    "engine": "5.3L V8",
    "power": "355 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Inspección mecánica rigurosa de 150 puntos",
      "Documentación y transferencia garantizada",
      "Garantía técnica de 6 meses RG Motors",
      "Financiamiento y retoma de vehículos en parte de pago"
    ]
  }
];

export const HERO_SHOWCASE_VEHICLES: Vehicle[] = initialVehicles.filter(v => v.featured).slice(0, 6);

export const vehicles: Vehicle[] = initialVehicles;

export function getVehicle(slug: string): Vehicle | undefined {
  return vehicles.find((v) => v.slug === slug);
}

export function formatCLP(amount: number): string {
  if (!amount || amount <= 0) return "Consultar precio";
  return new Intl.NumberFormat("es-CL", {
    style: "currency",
    currency: "CLP",
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatKm(km: number): string {
  return new Intl.NumberFormat("es-CL").format(km) + " km";
}

export function estimateMonthly(price: number, termMonths = 48, piePercent = 0.2): number {
  if (!price || price <= 0) return 0;
  const financed = price * (1 - piePercent);
  const monthlyRate = 0.0129; // ~1.29% mensual
  const factor = (monthlyRate * Math.pow(1 + monthlyRate, termMonths)) / (Math.pow(1 + monthlyRate, termMonths) - 1);
  return Math.round(financed * factor);
}

export function spinFramesOf(v: Vehicle): string[] {
  if (!v.spin || v.spin.count <= 0) return [];
  const { count, pattern = "" } = v.spin;
  return Array.from({ length: count }, (_, i) =>
    pattern ? pattern.replace("{index}", String(i + 1).padStart(3, "0")) : ""
  ).filter(Boolean);
}

export function specsOf(v: Vehicle): { label: string; value: string }[] {
  return [
    { label: "Kilometraje", value: `${v.km.toLocaleString("es-CL")} km` },
    { label: "Año", value: String(v.year) },
    { label: "Combustible", value: v.fuel },
    { label: "Transmisión", value: v.transmission },
    { label: "Potencia", value: v.power },
    { label: "Dueños", value: String(v.owners) },
    { label: "Puertas", value: String(v.doors) },
    { label: "Ubicación", value: v.location },
  ];
}

export const BRANDS = [
  "Toyota",
  "Mitsubishi",
  "Chevrolet",
  "Nissan",
  "Great Wall",
  "Peugeot",
  "Fiat",
  "Hyundai",
  "Subaru",
  "Renault",
  "DFSK",
  "Mercedes-Benz",
  "Ford",
  "Volkswagen",
  "Kia",
  "Suzuki",
  "Maxus",
  "MG",
  "SsangYong",
  "Omoda",
  "Changan",
  "Hino",
  "RAM",
  "JAC",
  "Otro",
];

export const BODY_TYPES = [
  "Pickup",
  "SUV",
  "Furgón",
  "Sedán",
  "Hatchback",
  "Camión",
  "Station Wagon",
  "Otro",
];

export const FUELS = ["Diésel", "Bencina", "Híbrido", "Eléctrico"];

export const TRANSMISSIONS = ["Automática", "Manual"];

export const STATUS_TYPES = ["Disponible", "En reserva", "Vendido", "Borrador", "En preparación"] as const;
