// 100% Authentic RG Motors Stock from Official Inventory
export interface VehicleSpin {
  count: number;
  pattern?: string;
  ext?: string;
}

export interface Vehicle {
  slug: string;
  plate?: string;
  brand: string;
  model: string;
  version: string;
  year: number;
  price: number;
  listPrice?: number;
  km: number;
  fuel: string;
  transmission: string;
  bodyType: string;
  location: string;
  image: string;
  gallery?: string[];
  spin?: VehicleSpin;
  engine: string;
  power: string;
  traction: string;
  doors: number;
  owners: number;
  featured?: boolean;
  status?: "Disponible" | "En reserva" | "Vendido" | "Borrador" | "En preparación";
  hasRealPhotos?: boolean;
  supplier?: string;
  techReview?: string;
  circPermit?: string;
  highlights?: string[];
}

export const initialVehicles: Vehicle[] = [
  {
    "slug": "mitsubishi-new-katana-4x2-2023-srcp17",
    "plate": "SRCP 17",
    "brand": "Mitsubishi",
    "model": "NEW KATANA 4X2",
    "version": "NEW KATANA 4X2 · Rojo",
    "year": 2023,
    "price": 13990000,
    "listPrice": 15490000,
    "km": 75000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/srcp17/0.jpg",
    "gallery": [
      "/cars/inventory/srcp17/0.jpg",
      "/cars/inventory/srcp17/1.jpg",
      "/cars/inventory/srcp17/2.jpg",
      "/cars/inventory/srcp17/3.jpg",
      "/cars/inventory/srcp17/4.jpg",
      "/cars/inventory/srcp17/5.jpg",
      "/cars/inventory/srcp17/6.jpg",
      "/cars/inventory/srcp17/7.jpg",
      "/cars/inventory/srcp17/8.jpg",
      "/cars/inventory/srcp17/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "octubre 2027",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x4-2020-lxcy98",
    "plate": "LXCY 98",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4x4",
    "version": "L200 KATANA 4x4 · Rojo",
    "year": 2020,
    "price": 13490000,
    "listPrice": 14490000,
    "km": 156000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/lxcy98/0.jpg",
    "gallery": [
      "/cars/inventory/lxcy98/0.jpg",
      "/cars/inventory/lxcy98/1.jpg",
      "/cars/inventory/lxcy98/2.jpg",
      "/cars/inventory/lxcy98/3.jpg",
      "/cars/inventory/lxcy98/4.jpg",
      "/cars/inventory/lxcy98/5.jpg",
      "/cars/inventory/lxcy98/6.jpg",
      "/cars/inventory/lxcy98/7.jpg",
      "/cars/inventory/lxcy98/8.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RQ RUDY CON IVA",
    "techReview": "NOVIEMBRE",
    "circPermit": "MARZO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "toyota-new-hilux-4x2-2022-rpkd45",
    "plate": "RPKD 45",
    "brand": "Toyota",
    "model": "NEW HILUX 4X2",
    "version": "NEW HILUX 4X2 · Rojo",
    "year": 2022,
    "price": 14990000,
    "listPrice": 15990000,
    "km": 135704,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/rpkd45/0.jpg",
    "gallery": [
      "/cars/inventory/rpkd45/0.jpg",
      "/cars/inventory/rpkd45/1.jpg",
      "/cars/inventory/rpkd45/2.jpg",
      "/cars/inventory/rpkd45/3.jpg",
      "/cars/inventory/rpkd45/4.jpg",
      "/cars/inventory/rpkd45/5.jpg",
      "/cars/inventory/rpkd45/6.jpg",
      "/cars/inventory/rpkd45/7.jpg",
      "/cars/inventory/rpkd45/8.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "AGOSTO",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "toyota-hilux-4x4-2022-rzvk91",
    "plate": "RZVK 91",
    "brand": "Toyota",
    "model": "HILUX 4X4",
    "version": "HILUX 4X4 · Rojo",
    "year": 2022,
    "price": 17990000,
    "listPrice": 18990000,
    "km": 151000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/rzvk91/0.jpg",
    "gallery": [
      "/cars/inventory/rzvk91/0.jpg",
      "/cars/inventory/rzvk91/1.jpg",
      "/cars/inventory/rzvk91/2.jpg",
      "/cars/inventory/rzvk91/3.jpg",
      "/cars/inventory/rzvk91/4.jpg",
      "/cars/inventory/rzvk91/5.jpg",
      "/cars/inventory/rzvk91/6.jpg",
      "/cars/inventory/rzvk91/7.jpg",
      "/cars/inventory/rzvk91/8.jpg",
      "/cars/inventory/rzvk91/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "CHARRIOT",
    "techReview": "octubre 2026",
    "circPermit": "MARZO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "toyota-raize-4x2-1-2-2025-tsgl82",
    "plate": "TSGL 82",
    "brand": "Toyota",
    "model": "RAIZE 4X2 1.2",
    "version": "RAIZE 4X2 1.2 · Gris",
    "year": 2025,
    "price": 12490000,
    "listPrice": 13490000,
    "km": 16000,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/tsgl82/0.jpg",
    "gallery": [
      "/cars/inventory/tsgl82/0.jpg",
      "/cars/inventory/tsgl82/1.jpg",
      "/cars/inventory/tsgl82/2.jpg",
      "/cars/inventory/tsgl82/3.jpg",
      "/cars/inventory/tsgl82/4.jpg",
      "/cars/inventory/tsgl82/5.jpg",
      "/cars/inventory/tsgl82/6.jpg",
      "/cars/inventory/tsgl82/7.jpg",
      "/cars/inventory/tsgl82/8.jpg",
      "/cars/inventory/tsgl82/9.jpg"
    ],
    "engine": "1.2L Dual VVT-i",
    "power": "87 HP",
    "traction": "4x2",
    "doors": 5,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RUDY",
    "techReview": "MAYO",
    "circPermit": "MARZO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "peugeot-partner-1-6-2023-sfxy80",
    "plate": "SFXY 80",
    "brand": "Peugeot",
    "model": "PARTNER 1,6",
    "version": "PARTNER 1,6 · Blanco",
    "year": 2023,
    "price": 10490000,
    "listPrice": 11490000,
    "km": 119136,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/sfxy80/0.jpg",
    "gallery": [
      "/cars/inventory/sfxy80/0.jpg",
      "/cars/inventory/sfxy80/1.jpg",
      "/cars/inventory/sfxy80/2.jpg",
      "/cars/inventory/sfxy80/3.jpg",
      "/cars/inventory/sfxy80/4.jpg",
      "/cars/inventory/sfxy80/5.jpg",
      "/cars/inventory/sfxy80/6.jpg",
      "/cars/inventory/sfxy80/7.jpg",
      "/cars/inventory/sfxy80/8.jpg",
      "/cars/inventory/sfxy80/9.jpg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "FEBRERO",
    "circPermit": "MARZO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "peugeot-partner-1-6-2022-scgj41",
    "plate": "SCGJ 41",
    "brand": "Peugeot",
    "model": "PARTNER 1.6",
    "version": "PARTNER 1.6 · Blanco",
    "year": 2022,
    "price": 11990000,
    "km": 110030,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/scgj41/0.jpg",
    "gallery": [
      "/cars/inventory/scgj41/0.jpg",
      "/cars/inventory/scgj41/1.jpg",
      "/cars/inventory/scgj41/2.jpg",
      "/cars/inventory/scgj41/3.jpg",
      "/cars/inventory/scgj41/4.jpg",
      "/cars/inventory/scgj41/5.jpg",
      "/cars/inventory/scgj41/6.jpg",
      "/cars/inventory/scgj41/7.jpg",
      "/cars/inventory/scgj41/8.jpg",
      "/cars/inventory/scgj41/9.jpg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": true,
    "status": "En reserva",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "ABRIL",
    "circPermit": "MARZO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "peugeot-partner-2021-psjj97",
    "plate": "PSJJ 97",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2021,
    "price": 8990000,
    "listPrice": 10490000,
    "km": 104900,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/psjj97/0.jpg",
    "gallery": [
      "/cars/inventory/psjj97/0.jpg",
      "/cars/inventory/psjj97/1.jpg",
      "/cars/inventory/psjj97/2.jpg",
      "/cars/inventory/psjj97/3.jpg",
      "/cars/inventory/psjj97/4.jpg",
      "/cars/inventory/psjj97/5.jpg",
      "/cars/inventory/psjj97/6.jpg",
      "/cars/inventory/psjj97/7.jpg",
      "/cars/inventory/psjj97/8.jpg",
      "/cars/inventory/psjj97/9.jpg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "OCTUBRE",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "peugeot-partner-2025-tsxk53",
    "plate": "TSXK53",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2025,
    "price": 12990000,
    "listPrice": 13990000,
    "km": 70000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/tsxk53/0.jpg",
    "gallery": [
      "/cars/inventory/tsxk53/0.jpg",
      "/cars/inventory/tsxk53/1.jpg",
      "/cars/inventory/tsxk53/2.jpg",
      "/cars/inventory/tsxk53/3.jpg",
      "/cars/inventory/tsxk53/4.jpg",
      "/cars/inventory/tsxk53/5.jpg",
      "/cars/inventory/tsxk53/6.jpg",
      "/cars/inventory/tsxk53/7.jpg",
      "/cars/inventory/tsxk53/8.jpg",
      "/cars/inventory/tsxk53/9.jpg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RELSA RG MOTORS",
    "techReview": "JUNIO",
    "circPermit": "MARZO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "peugeot-partner-2021-pysy84",
    "plate": "PYSY 84",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2021,
    "price": 8990000,
    "listPrice": 10990000,
    "km": 122000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/pysy84/0.jpg",
    "gallery": [
      "/cars/inventory/pysy84/0.jpg",
      "/cars/inventory/pysy84/1.jpg",
      "/cars/inventory/pysy84/2.jpg",
      "/cars/inventory/pysy84/3.jpg",
      "/cars/inventory/pysy84/4.jpg",
      "/cars/inventory/pysy84/5.jpg",
      "/cars/inventory/pysy84/6.jpg",
      "/cars/inventory/pysy84/7.jpg",
      "/cars/inventory/pysy84/8.jpg",
      "/cars/inventory/pysy84/9.jpg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION RG",
    "techReview": "JULIO",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "volkswagen-saveiro-dc-2023-sfrt83",
    "plate": "SFRT 83",
    "brand": "Volkswagen",
    "model": "SAVEIRO DC",
    "version": "SAVEIRO DC · Blanco",
    "year": 2023,
    "price": 9990000,
    "listPrice": 10990000,
    "km": 69000,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/sfrt83/0.jpg",
    "gallery": [
      "/cars/inventory/sfrt83/0.jpg",
      "/cars/inventory/sfrt83/1.jpg",
      "/cars/inventory/sfrt83/2.jpg",
      "/cars/inventory/sfrt83/3.jpg",
      "/cars/inventory/sfrt83/4.jpg",
      "/cars/inventory/sfrt83/5.jpg",
      "/cars/inventory/sfrt83/6.jpg",
      "/cars/inventory/sfrt83/7.jpg",
      "/cars/inventory/sfrt83/8.jpg",
      "/cars/inventory/sfrt83/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "JUNIO",
    "circPermit": "MARZO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "maxus-t60-4x2-at-2023-stpz87",
    "plate": "STPZ 87",
    "brand": "Maxus",
    "model": "T60 4X2 AT",
    "version": "T60 4X2 AT · Gris",
    "year": 2023,
    "price": 12990000,
    "listPrice": 14990000,
    "km": 78000,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/stpz87/0.jpg",
    "gallery": [
      "/cars/inventory/stpz87/0.jpg",
      "/cars/inventory/stpz87/1.jpg",
      "/cars/inventory/stpz87/2.jpg",
      "/cars/inventory/stpz87/3.jpg",
      "/cars/inventory/stpz87/4.jpg",
      "/cars/inventory/stpz87/5.jpg",
      "/cars/inventory/stpz87/6.jpg",
      "/cars/inventory/stpz87/7.jpg",
      "/cars/inventory/stpz87/8.jpg",
      "/cars/inventory/stpz87/9.jpg"
    ],
    "engine": "2.0L VGT Turbo Diésel",
    "power": "163 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "octubre 2027",
    "circPermit": "MARZO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "maxus-t60-dx-4x4-2023-ssdt39",
    "plate": "SSDT 39",
    "brand": "Maxus",
    "model": "T60 DX 4X4",
    "version": "T60 DX 4X4 · Rojo",
    "year": 2023,
    "price": 10990000,
    "listPrice": 11990000,
    "km": 134000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/ssdt39/0.jpg",
    "gallery": [
      "/cars/inventory/ssdt39/0.jpg",
      "/cars/inventory/ssdt39/1.jpg",
      "/cars/inventory/ssdt39/2.jpg",
      "/cars/inventory/ssdt39/3.jpg",
      "/cars/inventory/ssdt39/4.jpg",
      "/cars/inventory/ssdt39/5.jpg",
      "/cars/inventory/ssdt39/6.jpg",
      "/cars/inventory/ssdt39/7.jpg",
      "/cars/inventory/ssdt39/8.jpg",
      "/cars/inventory/ssdt39/9.jpg"
    ],
    "engine": "2.0L VGT Turbo Diésel",
    "power": "163 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "MITTA BANCO",
    "techReview": "ENERO",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mg-3-hatch-back-2022-rygb56",
    "plate": "RYGB 56",
    "brand": "MG",
    "model": "3 HATCH BACK",
    "version": "3 HATCH BACK · Blanco",
    "year": 2022,
    "price": 7490000,
    "listPrice": 8490000,
    "km": 60900,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Hatchback",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/rygb56/0.jpg",
    "gallery": [
      "/cars/inventory/rygb56/0.jpg",
      "/cars/inventory/rygb56/1.jpg",
      "/cars/inventory/rygb56/2.jpg",
      "/cars/inventory/rygb56/3.jpg",
      "/cars/inventory/rygb56/4.jpg",
      "/cars/inventory/rygb56/5.jpg",
      "/cars/inventory/rygb56/6.jpg",
      "/cars/inventory/rygb56/7.jpg",
      "/cars/inventory/rygb56/8.jpg",
      "/cars/inventory/rygb56/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 5,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RELSA RG MOTORS",
    "techReview": "SEPTIEMBRE",
    "circPermit": "marzo 2027",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "chevrolet-dmax-4x2-2020-lxbc60",
    "plate": "LXBC 60",
    "brand": "Chevrolet",
    "model": "DMAX 4X2",
    "version": "DMAX 4X2 · Rojo",
    "year": 2020,
    "price": 10990000,
    "listPrice": 11990000,
    "km": 195000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/lxbc60/0.jpg",
    "gallery": [
      "/cars/inventory/lxbc60/0.jpg",
      "/cars/inventory/lxbc60/1.jpg",
      "/cars/inventory/lxbc60/2.jpg",
      "/cars/inventory/lxbc60/3.jpg",
      "/cars/inventory/lxbc60/4.jpg",
      "/cars/inventory/lxbc60/5.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "MITTA BANCO",
    "techReview": "FEBRERO",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "chevrolet-colorado-4x4-2022-rzsy35",
    "plate": "RZSY 35",
    "brand": "Chevrolet",
    "model": "COLORADO 4X4",
    "version": "COLORADO 4X4 · Blanco",
    "year": 2022,
    "price": 16990000,
    "listPrice": 17990000,
    "km": 144800,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/rzsy35/0.jpg",
    "gallery": [
      "/cars/inventory/rzsy35/0.jpg",
      "/cars/inventory/rzsy35/1.jpg",
      "/cars/inventory/rzsy35/2.jpg",
      "/cars/inventory/rzsy35/3.jpg",
      "/cars/inventory/rzsy35/4.jpg",
      "/cars/inventory/rzsy35/5.jpg",
      "/cars/inventory/rzsy35/6.jpg",
      "/cars/inventory/rzsy35/7.jpg",
      "/cars/inventory/rzsy35/8.jpg",
      "/cars/inventory/rzsy35/9.jpg"
    ],
    "engine": "2.8L Duramax Turbo Diésel",
    "power": "200 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION RG",
    "techReview": "AGOSTO",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "ford-ranger-4x4-2023-shyl53",
    "plate": "SHYL 53",
    "brand": "Ford",
    "model": "RANGER 4X4",
    "version": "RANGER 4X4 · Rojo",
    "year": 2023,
    "price": 15990000,
    "listPrice": 16990000,
    "km": 104628,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/shyl53/0.jpg",
    "gallery": [
      "/cars/inventory/shyl53/0.jpg",
      "/cars/inventory/shyl53/1.jpg",
      "/cars/inventory/shyl53/2.jpg",
      "/cars/inventory/shyl53/3.jpg",
      "/cars/inventory/shyl53/4.jpg",
      "/cars/inventory/shyl53/5.jpg",
      "/cars/inventory/shyl53/6.jpg",
      "/cars/inventory/shyl53/7.jpg",
      "/cars/inventory/shyl53/8.jpg",
      "/cars/inventory/shyl53/9.jpg"
    ],
    "engine": "3.2L Duratorq TDCi 5-Cil",
    "power": "200 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "JUNIO",
    "circPermit": "MARZO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "ssangyong-musso-grand-4x2-2021-rdhb85",
    "plate": "RDHB 85",
    "brand": "SsangYong",
    "model": "MUSSO GRAND 4X2",
    "version": "MUSSO GRAND 4X2 · Gris",
    "year": 2021,
    "price": 11990000,
    "listPrice": 12990000,
    "km": 156000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Unidades Chile",
    "image": "/cars/inventory/rdhb85/0.jpg",
    "gallery": [
      "/cars/inventory/rdhb85/0.jpg",
      "/cars/inventory/rdhb85/1.jpg",
      "/cars/inventory/rdhb85/2.jpg",
      "/cars/inventory/rdhb85/3.jpg",
      "/cars/inventory/rdhb85/4.jpg",
      "/cars/inventory/rdhb85/5.jpg",
      "/cars/inventory/rdhb85/6.jpg",
      "/cars/inventory/rdhb85/7.jpg",
      "/cars/inventory/rdhb85/8.jpg",
      "/cars/inventory/rdhb85/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RQ RUDY CON IVA",
    "techReview": "AGOSTO",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x2-2022-rhkd26",
    "plate": "RHKD 26",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X2",
    "version": "L200 KATANA 4X2 · Rojo",
    "year": 2022,
    "price": 13490000,
    "listPrice": 14490000,
    "km": 139000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/rhkd26/0.jpg",
    "gallery": [
      "/cars/inventory/rhkd26/0.jpg",
      "/cars/inventory/rhkd26/1.jpg",
      "/cars/inventory/rhkd26/2.jpg",
      "/cars/inventory/rhkd26/3.jpg",
      "/cars/inventory/rhkd26/4.jpg",
      "/cars/inventory/rhkd26/5.jpg",
      "/cars/inventory/rhkd26/6.jpg",
      "/cars/inventory/rhkd26/7.jpg",
      "/cars/inventory/rhkd26/8.jpg",
      "/cars/inventory/rhkd26/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RQ RUDY CON IVA",
    "techReview": "SEPTIEMBRE",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mitsubishi-katana-4x2-2024-thzf75",
    "plate": "THZF 75",
    "brand": "Mitsubishi",
    "model": "KATANA 4X2",
    "version": "KATANA 4X2 · Rojo",
    "year": 2024,
    "price": 14990000,
    "listPrice": 15990000,
    "km": 65000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/thzf75/0.jpg",
    "gallery": [
      "/cars/inventory/thzf75/0.jpg",
      "/cars/inventory/thzf75/1.jpg",
      "/cars/inventory/thzf75/2.jpg",
      "/cars/inventory/thzf75/3.jpg",
      "/cars/inventory/thzf75/4.jpg",
      "/cars/inventory/thzf75/5.jpg",
      "/cars/inventory/thzf75/6.jpg",
      "/cars/inventory/thzf75/7.jpg",
      "/cars/inventory/thzf75/8.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "agosto 2026",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mitsubishi-katana-work-4x2-2022-rggz96",
    "plate": "RGGZ 96",
    "brand": "Mitsubishi",
    "model": "KATANA WORK 4X2",
    "version": "KATANA WORK 4X2 · Blanco",
    "year": 2022,
    "price": 13990000,
    "listPrice": 14990000,
    "km": 148386,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/rggz96/0.jpg",
    "gallery": [
      "/cars/inventory/rggz96/0.jpg",
      "/cars/inventory/rggz96/1.jpg",
      "/cars/inventory/rggz96/2.jpg",
      "/cars/inventory/rggz96/3.jpg",
      "/cars/inventory/rggz96/4.jpg",
      "/cars/inventory/rggz96/5.jpg",
      "/cars/inventory/rggz96/6.jpg",
      "/cars/inventory/rggz96/7.jpg",
      "/cars/inventory/rggz96/8.jpg",
      "/cars/inventory/rggz96/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "CONSIGNADO",
    "techReview": "SEPTIEMBRE",
    "circPermit": "MARZO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mitsubishi-katana-4x4-2023-sgvc26",
    "plate": "SGVC 26",
    "brand": "Mitsubishi",
    "model": "KATANA 4X4",
    "version": "KATANA 4X4 · Rojo",
    "year": 2023,
    "price": 11990000,
    "km": 231741,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/sgvc26/0.jpg",
    "gallery": [
      "/cars/inventory/sgvc26/0.jpg",
      "/cars/inventory/sgvc26/1.jpg",
      "/cars/inventory/sgvc26/2.jpg",
      "/cars/inventory/sgvc26/3.jpg",
      "/cars/inventory/sgvc26/4.jpg",
      "/cars/inventory/sgvc26/5.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "En preparación",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "SEPTIEMBRE",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x4-2020-pgbv10",
    "plate": "PGBV 10",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X4",
    "version": "L200 KATANA 4X4 · Rojo",
    "year": 2020,
    "price": 12990000,
    "listPrice": 13990000,
    "km": 208401,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": false,
    "supplier": "RQ RUDY CON IVA",
    "techReview": "FALTA DOCUME.",
    "circPermit": "FALTA DOCUME.",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x2-2021-rbfk40",
    "plate": "RBFK 40",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X2",
    "version": "L200 KATANA 4X2 · Rojo",
    "year": 2021,
    "price": 11990000,
    "km": 182825,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": false,
    "supplier": "RQ RUDY CON IVA",
    "techReview": "febrero 2027",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "toyota-hilux-4x2-2023-swdv33",
    "plate": "SWDV 33",
    "brand": "Toyota",
    "model": "HILUX 4X2",
    "version": "HILUX 4X2 · Rojo",
    "year": 2023,
    "price": 15990000,
    "listPrice": 16990000,
    "km": 159378,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/swdv33/0.jpg",
    "gallery": [
      "/cars/inventory/swdv33/0.jpg",
      "/cars/inventory/swdv33/1.jpg",
      "/cars/inventory/swdv33/2.jpg",
      "/cars/inventory/swdv33/3.jpg",
      "/cars/inventory/swdv33/4.jpg",
      "/cars/inventory/swdv33/5.jpg",
      "/cars/inventory/swdv33/6.jpg",
      "/cars/inventory/swdv33/7.jpg",
      "/cars/inventory/swdv33/8.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RUDY",
    "techReview": "junio 2027",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "toyota-hilux-sr-4x4-2022-rwyr12",
    "plate": "RWYR 12",
    "brand": "Toyota",
    "model": "HILUX SR 4X4",
    "version": "HILUX SR 4X4 · Rojo",
    "year": 2022,
    "price": 22990000,
    "listPrice": 23990000,
    "km": 84000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/rwyr12/0.jpg",
    "gallery": [
      "/cars/inventory/rwyr12/0.jpg",
      "/cars/inventory/rwyr12/1.jpg",
      "/cars/inventory/rwyr12/2.jpg",
      "/cars/inventory/rwyr12/3.jpg",
      "/cars/inventory/rwyr12/4.jpg",
      "/cars/inventory/rwyr12/5.jpg",
      "/cars/inventory/rwyr12/6.jpg",
      "/cars/inventory/rwyr12/7.jpg",
      "/cars/inventory/rwyr12/8.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RUDY",
    "techReview": "mayo 2026",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "toyota-hilux-sr-4x4-2024-thsr65",
    "plate": "THSR 65",
    "brand": "Toyota",
    "model": "HILUX SR 4X4",
    "version": "HILUX SR 4X4 · Roja",
    "year": 2024,
    "price": 24990000,
    "listPrice": 25990000,
    "km": 90386,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/thsr65/0.jpg",
    "gallery": [
      "/cars/inventory/thsr65/0.jpg",
      "/cars/inventory/thsr65/1.jpg",
      "/cars/inventory/thsr65/2.jpg",
      "/cars/inventory/thsr65/3.jpg",
      "/cars/inventory/thsr65/4.jpg",
      "/cars/inventory/thsr65/5.jpg",
      "/cars/inventory/thsr65/6.jpg",
      "/cars/inventory/thsr65/7.jpg",
      "/cars/inventory/thsr65/8.jpg",
      "/cars/inventory/thsr65/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "AGOSTO",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "peugeot-partner-hdi-92-l1-1-6-2022-sbzc70",
    "plate": "SBZC 70",
    "brand": "Peugeot",
    "model": "PARTNER HDI 92 L1 1.6",
    "version": "PARTNER HDI 92 L1 1.6 · Blanco",
    "year": 2022,
    "price": 150104,
    "km": 2027,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/sbzc70/0.jpg",
    "gallery": [
      "/cars/inventory/sbzc70/0.jpg",
      "/cars/inventory/sbzc70/1.jpg",
      "/cars/inventory/sbzc70/2.jpg",
      "/cars/inventory/sbzc70/3.jpg",
      "/cars/inventory/sbzc70/4.jpg",
      "/cars/inventory/sbzc70/5.jpg",
      "/cars/inventory/sbzc70/6.jpg",
      "/cars/inventory/sbzc70/7.jpg",
      "/cars/inventory/sbzc70/8.jpg",
      "/cars/inventory/sbzc70/9.jpg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "AGOSTO",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "peugeot-partner-2022-rlvr63",
    "plate": "RLVR 63",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2022,
    "price": 7990000,
    "listPrice": 8990000,
    "km": 246000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/rlvr63/0.jpg",
    "gallery": [
      "/cars/inventory/rlvr63/0.jpg",
      "/cars/inventory/rlvr63/1.jpg",
      "/cars/inventory/rlvr63/2.jpg",
      "/cars/inventory/rlvr63/3.jpg",
      "/cars/inventory/rlvr63/4.jpg",
      "/cars/inventory/rlvr63/5.jpg",
      "/cars/inventory/rlvr63/6.jpg",
      "/cars/inventory/rlvr63/7.jpg",
      "/cars/inventory/rlvr63/8.jpg",
      "/cars/inventory/rlvr63/9.jpg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "junio 2027",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "peugeot-partner-2022-scgv34",
    "plate": "SCGV 34",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2022,
    "price": 9490000,
    "listPrice": 10490000,
    "km": 108806,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/scgv34/0.jpg",
    "gallery": [
      "/cars/inventory/scgv34/0.jpg",
      "/cars/inventory/scgv34/1.jpg",
      "/cars/inventory/scgv34/2.jpg",
      "/cars/inventory/scgv34/3.jpg",
      "/cars/inventory/scgv34/4.jpg",
      "/cars/inventory/scgv34/5.jpg",
      "/cars/inventory/scgv34/6.jpg",
      "/cars/inventory/scgv34/7.jpg",
      "/cars/inventory/scgv34/8.jpg",
      "/cars/inventory/scgv34/9.jpg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "peugeot-partner-2023-svfb26",
    "plate": "SVFB 26",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2023,
    "price": 10490000,
    "km": 89498,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "peugeot-expert-2022-scdw37",
    "plate": "SCDW 37",
    "brand": "Peugeot",
    "model": "EXPERT",
    "version": "EXPERT · Blanco",
    "year": 2022,
    "price": 10990000,
    "listPrice": 11990000,
    "km": 236400,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/scdw37/0.jpg",
    "gallery": [
      "/cars/inventory/scdw37/0.jpg",
      "/cars/inventory/scdw37/1.jpg",
      "/cars/inventory/scdw37/2.jpg",
      "/cars/inventory/scdw37/3.jpg",
      "/cars/inventory/scdw37/4.jpg",
      "/cars/inventory/scdw37/5.jpg",
      "/cars/inventory/scdw37/6.jpg",
      "/cars/inventory/scdw37/7.jpg",
      "/cars/inventory/scdw37/8.jpg",
      "/cars/inventory/scdw37/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "SEPTIEMBRE",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "peugeot-partner-1-6-2022-rlvr54",
    "plate": "RLVR 54",
    "brand": "Peugeot",
    "model": "PARTNER 1,6",
    "version": "PARTNER 1,6 · Blanco",
    "year": 2022,
    "price": 8990000,
    "listPrice": 9990000,
    "km": 159176,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/rlvr54/0.jpg",
    "gallery": [
      "/cars/inventory/rlvr54/0.jpg",
      "/cars/inventory/rlvr54/1.jpg",
      "/cars/inventory/rlvr54/2.jpg",
      "/cars/inventory/rlvr54/3.jpg",
      "/cars/inventory/rlvr54/4.jpg",
      "/cars/inventory/rlvr54/5.jpg",
      "/cars/inventory/rlvr54/6.jpg",
      "/cars/inventory/rlvr54/7.jpg",
      "/cars/inventory/rlvr54/8.jpg",
      "/cars/inventory/rlvr54/9.jpg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION RG",
    "techReview": "julio 2026",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "peugeot-partner-2023-ssdd57",
    "plate": "SSDD 57",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2023,
    "price": 9990000,
    "km": 152557,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/ssdd57/0.jpg",
    "gallery": [
      "/cars/inventory/ssdd57/0.jpg",
      "/cars/inventory/ssdd57/1.jpg",
      "/cars/inventory/ssdd57/2.jpg",
      "/cars/inventory/ssdd57/3.jpg",
      "/cars/inventory/ssdd57/4.jpg",
      "/cars/inventory/ssdd57/5.jpg",
      "/cars/inventory/ssdd57/6.jpg",
      "/cars/inventory/ssdd57/7.jpg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "peugeot-partner-1-6-2022-rzdc35",
    "plate": "RZDC 35",
    "brand": "Peugeot",
    "model": "PARTNER 1,6",
    "version": "PARTNER 1,6 · Blanco",
    "year": 2022,
    "price": 9490000,
    "km": 120000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/rzdc35/0.jpg",
    "gallery": [
      "/cars/inventory/rzdc35/0.jpg",
      "/cars/inventory/rzdc35/1.jpg",
      "/cars/inventory/rzdc35/2.jpg",
      "/cars/inventory/rzdc35/3.jpg",
      "/cars/inventory/rzdc35/4.jpg",
      "/cars/inventory/rzdc35/5.jpg",
      "/cars/inventory/rzdc35/6.jpg",
      "/cars/inventory/rzdc35/7.jpg",
      "/cars/inventory/rzdc35/8.jpg",
      "/cars/inventory/rzdc35/9.jpg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "agosto 2026",
    "techReview": "AGOSTO",
    "circPermit": "CARDONAL",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "nissan-navara-4x2-2023-sjtd29",
    "plate": "SJTD 29",
    "brand": "Nissan",
    "model": "NAVARA 4X2",
    "version": "NAVARA 4X2 · Gris",
    "year": 2023,
    "price": 15990000,
    "listPrice": 17990000,
    "km": 80000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Salgado",
    "image": "/cars/inventory/sjtd29/0.jpg",
    "gallery": [
      "/cars/inventory/sjtd29/0.jpg",
      "/cars/inventory/sjtd29/1.jpg",
      "/cars/inventory/sjtd29/2.jpg",
      "/cars/inventory/sjtd29/3.jpg",
      "/cars/inventory/sjtd29/4.jpg",
      "/cars/inventory/sjtd29/5.jpg",
      "/cars/inventory/sjtd29/6.jpg",
      "/cars/inventory/sjtd29/7.jpg",
      "/cars/inventory/sjtd29/8.jpg",
      "/cars/inventory/sjtd29/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RUDY",
    "techReview": "ENERO",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "nissan-navara-xe-4x2-2024-tcgb98",
    "plate": "TCGB 98",
    "brand": "Nissan",
    "model": "NAVARA XE 4X2",
    "version": "NAVARA XE 4X2 · Roja",
    "year": 2024,
    "price": 15990000,
    "listPrice": 17990000,
    "km": 125518,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/tcgb98/0.jpg",
    "gallery": [
      "/cars/inventory/tcgb98/0.jpg",
      "/cars/inventory/tcgb98/1.jpg",
      "/cars/inventory/tcgb98/2.jpg",
      "/cars/inventory/tcgb98/3.jpg",
      "/cars/inventory/tcgb98/4.jpg",
      "/cars/inventory/tcgb98/5.jpg",
      "/cars/inventory/tcgb98/6.jpg",
      "/cars/inventory/tcgb98/7.jpg",
      "/cars/inventory/tcgb98/8.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "MAYO",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "nissan-navara-4x2-2024-tcpt20",
    "plate": "TCPT 20",
    "brand": "Nissan",
    "model": "NAVARA 4X2",
    "version": "NAVARA 4X2 · Rojo",
    "year": 2024,
    "price": 15990000,
    "listPrice": 17990000,
    "km": 51714,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/tcpt20/0.jpg",
    "gallery": [
      "/cars/inventory/tcpt20/0.jpg",
      "/cars/inventory/tcpt20/1.jpg",
      "/cars/inventory/tcpt20/2.jpg",
      "/cars/inventory/tcpt20/3.jpg",
      "/cars/inventory/tcpt20/4.jpg",
      "/cars/inventory/tcpt20/5.jpg",
      "/cars/inventory/tcpt20/6.jpg",
      "/cars/inventory/tcpt20/7.jpg",
      "/cars/inventory/tcpt20/8.jpg",
      "/cars/inventory/tcpt20/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RUDY",
    "techReview": "febrero 2028",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "ford-raptor-f150-2020-lrjy32",
    "plate": "LRJY 32",
    "brand": "Ford",
    "model": "RAPTOR F150",
    "version": "RAPTOR F150 · Rojo",
    "year": 2020,
    "price": 39990000,
    "km": 136279,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/lrjy32/0.jpg",
    "gallery": [
      "/cars/inventory/lrjy32/0.jpg",
      "/cars/inventory/lrjy32/1.jpg",
      "/cars/inventory/lrjy32/2.jpg",
      "/cars/inventory/lrjy32/3.jpg",
      "/cars/inventory/lrjy32/4.jpg",
      "/cars/inventory/lrjy32/5.jpg",
      "/cars/inventory/lrjy32/6.jpg",
      "/cars/inventory/lrjy32/7.jpg",
      "/cars/inventory/lrjy32/8.jpg",
      "/cars/inventory/lrjy32/9.jpg"
    ],
    "engine": "3.5L EcoBoost Twin-Turbo V6",
    "power": "450 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RUDY",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "volkswagen-saveiro-dcab-2023-sfrx48",
    "plate": "SFRX 48",
    "brand": "Volkswagen",
    "model": "SAVEIRO DCAB",
    "version": "SAVEIRO DCAB · Blanco",
    "year": 2023,
    "price": 9990000,
    "listPrice": 10990000,
    "km": 59000,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/sfrx48/0.jpg",
    "gallery": [
      "/cars/inventory/sfrx48/0.jpg",
      "/cars/inventory/sfrx48/1.jpg",
      "/cars/inventory/sfrx48/2.jpg",
      "/cars/inventory/sfrx48/3.jpg",
      "/cars/inventory/sfrx48/4.jpg",
      "/cars/inventory/sfrx48/5.jpg",
      "/cars/inventory/sfrx48/6.jpg",
      "/cars/inventory/sfrx48/7.jpg",
      "/cars/inventory/sfrx48/8.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "NOVIEMBRE",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "volkswagen-saveiro-cd-1-6-2022-slgd85",
    "plate": "SLGD85",
    "brand": "Volkswagen",
    "model": "SAVEIRO CD 1.6",
    "version": "SAVEIRO CD 1.6 · Blanco",
    "year": 2022,
    "price": 11990000,
    "km": 120000,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/slgd85/0.jpg",
    "gallery": [
      "/cars/inventory/slgd85/0.jpg",
      "/cars/inventory/slgd85/1.jpg",
      "/cars/inventory/slgd85/2.jpg",
      "/cars/inventory/slgd85/3.jpg",
      "/cars/inventory/slgd85/4.jpg",
      "/cars/inventory/slgd85/5.jpg",
      "/cars/inventory/slgd85/6.jpg",
      "/cars/inventory/slgd85/7.jpg",
      "/cars/inventory/slgd85/8.jpg",
      "/cars/inventory/slgd85/9.jpg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "En preparación",
    "hasRealPhotos": true,
    "supplier": "CARDONAL",
    "techReview": "Al día",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "volkswagen-amarok-4x4-mt-2022-rrkb78",
    "plate": "RRKB 78",
    "brand": "Volkswagen",
    "model": "AMAROK 4X4 MT",
    "version": "AMAROK 4X4 MT · Blanco",
    "year": 2022,
    "price": 14990000,
    "listPrice": 15990000,
    "km": 207000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/rrkb78/0.jpg",
    "gallery": [
      "/cars/inventory/rrkb78/0.jpg",
      "/cars/inventory/rrkb78/1.jpg",
      "/cars/inventory/rrkb78/2.jpg",
      "/cars/inventory/rrkb78/3.jpg",
      "/cars/inventory/rrkb78/4.jpg",
      "/cars/inventory/rrkb78/5.jpg",
      "/cars/inventory/rrkb78/6.jpg",
      "/cars/inventory/rrkb78/7.jpg",
      "/cars/inventory/rrkb78/8.jpg",
      "/cars/inventory/rrkb78/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "noviembre 2026",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "hino-xzu-617-dc-2023-sklf13",
    "plate": "SKLF 13",
    "brand": "Hino",
    "model": "XZU 617 DC",
    "version": "XZU 617 DC · Blanco",
    "year": 2023,
    "price": 25990000,
    "listPrice": 26990000,
    "km": 103000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camión",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/sklf13/0.jpg",
    "gallery": [
      "/cars/inventory/sklf13/0.jpg",
      "/cars/inventory/sklf13/1.jpg",
      "/cars/inventory/sklf13/2.jpg",
      "/cars/inventory/sklf13/3.jpg",
      "/cars/inventory/sklf13/4.jpg",
      "/cars/inventory/sklf13/5.jpg",
      "/cars/inventory/sklf13/6.jpg",
      "/cars/inventory/sklf13/7.jpg",
      "/cars/inventory/sklf13/8.jpg",
      "/cars/inventory/sklf13/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "abril 2026",
    "circPermit": "SEPTIEMBRE",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "maxus-t60-4x4-glx-2022-sdds52",
    "plate": "SDDS 52",
    "brand": "Maxus",
    "model": "T60 4X4 GLX",
    "version": "T60 4X4 GLX · Blanco",
    "year": 2022,
    "price": 10990000,
    "listPrice": 11990000,
    "km": 190305,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/sdds52/0.jpg",
    "gallery": [
      "/cars/inventory/sdds52/0.jpg",
      "/cars/inventory/sdds52/1.jpg",
      "/cars/inventory/sdds52/2.jpg",
      "/cars/inventory/sdds52/3.jpg",
      "/cars/inventory/sdds52/4.jpg",
      "/cars/inventory/sdds52/5.jpg",
      "/cars/inventory/sdds52/6.jpg",
      "/cars/inventory/sdds52/7.jpg",
      "/cars/inventory/sdds52/8.jpg",
      "/cars/inventory/sdds52/9.jpg"
    ],
    "engine": "2.0L VGT Turbo Diésel",
    "power": "163 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "mayo 2027",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "ram-v700-2021-ptfc69",
    "plate": "PTFC 69",
    "brand": "RAM",
    "model": "V700",
    "version": "V700 · Blanco",
    "year": 2021,
    "price": 6990000,
    "listPrice": 7990000,
    "km": 141000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/ptfc69/0.jpg",
    "gallery": [
      "/cars/inventory/ptfc69/0.jpg",
      "/cars/inventory/ptfc69/1.jpg",
      "/cars/inventory/ptfc69/2.jpg",
      "/cars/inventory/ptfc69/3.jpg",
      "/cars/inventory/ptfc69/4.jpg",
      "/cars/inventory/ptfc69/5.jpg",
      "/cars/inventory/ptfc69/6.jpg",
      "/cars/inventory/ptfc69/7.jpg",
      "/cars/inventory/ptfc69/8.jpg",
      "/cars/inventory/ptfc69/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION RG",
    "techReview": "enero 2027",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "nissan-navara-4x4-2022-rhyh38",
    "plate": "RHYH 38",
    "brand": "Nissan",
    "model": "NAVARA 4X4",
    "version": "NAVARA 4X4 · Rojo",
    "year": 2022,
    "price": 15990000,
    "listPrice": 16990000,
    "km": 135000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/rhyh38/0.jpg",
    "gallery": [
      "/cars/inventory/rhyh38/0.jpg",
      "/cars/inventory/rhyh38/1.jpg",
      "/cars/inventory/rhyh38/2.jpg",
      "/cars/inventory/rhyh38/3.jpg",
      "/cars/inventory/rhyh38/4.jpg",
      "/cars/inventory/rhyh38/5.jpg",
      "/cars/inventory/rhyh38/6.jpg",
      "/cars/inventory/rhyh38/7.jpg",
      "/cars/inventory/rhyh38/8.jpg",
      "/cars/inventory/rhyh38/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "CHARRIOT",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "chevrolet-colorado-4x4-aut-2022-sfyb29",
    "plate": "SFYB 29",
    "brand": "Chevrolet",
    "model": "COLORADO 4X4 AUT.",
    "version": "COLORADO 4X4 AUT. · Blanco",
    "year": 2022,
    "price": 18990000,
    "listPrice": 19990000,
    "km": 111222,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/sfyb29/0.jpg",
    "gallery": [
      "/cars/inventory/sfyb29/0.jpg",
      "/cars/inventory/sfyb29/1.jpg",
      "/cars/inventory/sfyb29/2.jpg",
      "/cars/inventory/sfyb29/3.jpg",
      "/cars/inventory/sfyb29/4.jpg",
      "/cars/inventory/sfyb29/5.jpg",
      "/cars/inventory/sfyb29/6.jpg",
      "/cars/inventory/sfyb29/7.jpg",
      "/cars/inventory/sfyb29/8.jpg"
    ],
    "engine": "2.8L Duramax Turbo Diésel",
    "power": "200 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RELSA RG MOTORS",
    "techReview": "enero 2027",
    "circPermit": "VENCIDO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "chevrolet-colorado-4x4-aut-2022-sfbl43",
    "plate": "SFBL43",
    "brand": "Chevrolet",
    "model": "COLORADO 4X4 AUT.",
    "version": "COLORADO 4X4 AUT. · Blanco",
    "year": 2022,
    "price": 16990000,
    "listPrice": 17990000,
    "km": 149586,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/sfbl43/0.jpg",
    "gallery": [
      "/cars/inventory/sfbl43/0.jpg",
      "/cars/inventory/sfbl43/1.jpg",
      "/cars/inventory/sfbl43/2.jpg",
      "/cars/inventory/sfbl43/3.jpg",
      "/cars/inventory/sfbl43/4.jpg",
      "/cars/inventory/sfbl43/5.jpg",
      "/cars/inventory/sfbl43/6.jpg",
      "/cars/inventory/sfbl43/7.jpg",
      "/cars/inventory/sfbl43/8.jpg",
      "/cars/inventory/sfbl43/9.jpg"
    ],
    "engine": "2.8L Duramax Turbo Diésel",
    "power": "200 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "chevrolet-colorado-4x4-aut-2022-sdjt43",
    "plate": "SDJT 43",
    "brand": "Chevrolet",
    "model": "COLORADO 4X4 AUT.",
    "version": "COLORADO 4X4 AUT. · Blanco",
    "year": 2022,
    "price": 15990000,
    "listPrice": 16990000,
    "km": 177865,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "2.8L Duramax Turbo Diésel",
    "power": "200 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "chevrolet-dmax-4x4-2022-rpfs85",
    "plate": "RPFS 85",
    "brand": "Chevrolet",
    "model": "DMAX 4X4",
    "version": "DMAX 4X4 · Rojo",
    "year": 2022,
    "price": 13990000,
    "listPrice": 14990000,
    "km": 120000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": false,
    "supplier": "agosto 2026",
    "techReview": "AGOSTO",
    "circPermit": "CARDONAL",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "ssangyong-musso-grand-2021-rdhb71",
    "plate": "RDHB 71",
    "brand": "SsangYong",
    "model": "MUSSO GRAND",
    "version": "MUSSO GRAND · Gris",
    "year": 2021,
    "price": 11990000,
    "listPrice": 12990000,
    "km": 161404,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Salgado",
    "image": "/cars/inventory/rdhb71/0.jpg",
    "gallery": [
      "/cars/inventory/rdhb71/0.jpg",
      "/cars/inventory/rdhb71/1.jpg",
      "/cars/inventory/rdhb71/2.jpg",
      "/cars/inventory/rdhb71/3.jpg",
      "/cars/inventory/rdhb71/4.jpg",
      "/cars/inventory/rdhb71/5.jpg",
      "/cars/inventory/rdhb71/6.jpg",
      "/cars/inventory/rdhb71/7.jpg",
      "/cars/inventory/rdhb71/8.jpg",
      "/cars/inventory/rdhb71/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RQ RUDY CON IVA",
    "techReview": "FALTA DOCUME.",
    "circPermit": "FALTA DOCUME.",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "renault-duster-expression-1-6-2015-hbdz43",
    "plate": "HBDZ 43",
    "brand": "Renault",
    "model": "DUSTER EXPRESSION 1.6",
    "version": "DUSTER EXPRESSION 1.6 · Negro",
    "year": 2015,
    "price": 4990000,
    "listPrice": 5990000,
    "km": 122000,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/hbdz43/0.jpg",
    "gallery": [
      "/cars/inventory/hbdz43/0.jpg",
      "/cars/inventory/hbdz43/1.jpg",
      "/cars/inventory/hbdz43/2.jpg",
      "/cars/inventory/hbdz43/3.jpg",
      "/cars/inventory/hbdz43/4.jpg",
      "/cars/inventory/hbdz43/5.jpg",
      "/cars/inventory/hbdz43/6.jpg",
      "/cars/inventory/hbdz43/7.jpg",
      "/cars/inventory/hbdz43/8.jpg",
      "/cars/inventory/hbdz43/9.jpg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 5,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "C.PODER",
    "techReview": "JUNIO",
    "circPermit": "MARZO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mercedes-benz-ml300-cdi-2011-ddlj95",
    "plate": "DDLJ 95",
    "brand": "Mercedes-Benz",
    "model": "ML300 CDI",
    "version": "ML300 CDI · Blanco",
    "year": 2011,
    "price": 9490000,
    "listPrice": 10490000,
    "km": 216000,
    "fuel": "Bencina",
    "transmission": "Automática",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/ddlj95/0.jpg",
    "gallery": [
      "/cars/inventory/ddlj95/0.jpg",
      "/cars/inventory/ddlj95/1.jpg",
      "/cars/inventory/ddlj95/2.jpg",
      "/cars/inventory/ddlj95/3.jpg",
      "/cars/inventory/ddlj95/4.jpg",
      "/cars/inventory/ddlj95/5.jpg",
      "/cars/inventory/ddlj95/6.jpg",
      "/cars/inventory/ddlj95/7.jpg",
      "/cars/inventory/ddlj95/8.jpg",
      "/cars/inventory/ddlj95/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 5,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "C.PODER",
    "techReview": "AGOSTO",
    "circPermit": "marzo 2027",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "subaru-wrx-sti-4x4-2-5-2022-rkrg58",
    "plate": "RKRG 58",
    "brand": "Subaru",
    "model": "WRX STI 4X4 2.5",
    "version": "WRX STI 4X4 2.5 · Azul",
    "year": 2022,
    "price": 39990000,
    "listPrice": 40990000,
    "km": 120000,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Sedán",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/rkrg58/0.jpg",
    "gallery": [
      "/cars/inventory/rkrg58/0.jpg",
      "/cars/inventory/rkrg58/1.jpg",
      "/cars/inventory/rkrg58/2.jpg",
      "/cars/inventory/rkrg58/3.jpg",
      "/cars/inventory/rkrg58/4.jpg",
      "/cars/inventory/rkrg58/5.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RG Motors",
    "techReview": "Al día",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mitsubishi-l200-work-4x2-2021-pxsv97",
    "plate": "PXSV 97",
    "brand": "Mitsubishi",
    "model": "L200 WORK 4X2",
    "version": "L200 WORK 4X2 · Rojo",
    "year": 2021,
    "price": 12490000,
    "listPrice": 13490000,
    "km": 139113,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/pxsv97/0.jpg",
    "gallery": [
      "/cars/inventory/pxsv97/0.jpg",
      "/cars/inventory/pxsv97/1.jpg",
      "/cars/inventory/pxsv97/2.jpg",
      "/cars/inventory/pxsv97/3.jpg",
      "/cars/inventory/pxsv97/4.jpg",
      "/cars/inventory/pxsv97/5.jpg",
      "/cars/inventory/pxsv97/6.jpg",
      "/cars/inventory/pxsv97/7.jpg",
      "/cars/inventory/pxsv97/8.jpg",
      "/cars/inventory/pxsv97/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RQ RUDY CON IVA SIN REVISION/vence octubre",
    "techReview": "MARZO",
    "circPermit": "CARDONAL",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "nissan-navara-xe-4x4-2021-rdhl11",
    "plate": "RDHL 11",
    "brand": "Nissan",
    "model": "NAVARA XE 4X4",
    "version": "NAVARA XE 4X4 · Blanco",
    "year": 2021,
    "price": 16990000,
    "listPrice": 17990000,
    "km": 79538,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/rdhl11/0.jpg",
    "gallery": [
      "/cars/inventory/rdhl11/0.jpg",
      "/cars/inventory/rdhl11/1.jpg",
      "/cars/inventory/rdhl11/2.jpg",
      "/cars/inventory/rdhl11/3.jpg",
      "/cars/inventory/rdhl11/4.jpg",
      "/cars/inventory/rdhl11/5.jpg",
      "/cars/inventory/rdhl11/6.jpg",
      "/cars/inventory/rdhl11/7.jpg",
      "/cars/inventory/rdhl11/8.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RELSA RG MOTORS",
    "techReview": "ABRIL",
    "circPermit": "MARZO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "maxus-t60-4x2-2022-sfwd31",
    "plate": "SFWD 31",
    "brand": "Maxus",
    "model": "T60 4X2",
    "version": "T60 4X2 · Blanco",
    "year": 2022,
    "price": 9990000,
    "listPrice": 10990000,
    "km": 69379,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "2.0L VGT Turbo Diésel",
    "power": "163 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": false,
    "supplier": "MITTA BANCO",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "chevrolet-spark-gt-lt-1-2-2021-pgft56",
    "plate": "PGFT56",
    "brand": "Chevrolet",
    "model": "SPARK GT LT 1.2",
    "version": "SPARK GT LT 1.2 · Blanco",
    "year": 2021,
    "price": 11990000,
    "km": 58661,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Hatchback",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "1.2L Dual VVT-i",
    "power": "87 HP",
    "traction": "4x2",
    "doors": 5,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": false,
    "supplier": "C.PODER",
    "techReview": "SEPTIEMBRE",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "hyundai-porter-ii-2022-rpsh45",
    "plate": "RPSH 45",
    "brand": "Hyundai",
    "model": "PORTER II",
    "version": "PORTER II · Blanco",
    "year": 2022,
    "price": 14990000,
    "listPrice": 15990000,
    "km": 110000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camión",
    "location": "Puerto Montt · Sucursal Salgado",
    "image": "/cars/inventory/rpsh45/0.jpg",
    "gallery": [
      "/cars/inventory/rpsh45/0.jpg",
      "/cars/inventory/rpsh45/1.jpg",
      "/cars/inventory/rpsh45/2.jpg",
      "/cars/inventory/rpsh45/3.jpg",
      "/cars/inventory/rpsh45/4.jpg",
      "/cars/inventory/rpsh45/5.jpg",
      "/cars/inventory/rpsh45/6.jpg",
      "/cars/inventory/rpsh45/7.jpg",
      "/cars/inventory/rpsh45/8.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "En preparación",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION RG",
    "techReview": "AGOSTO",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "nissan-navara-se-4x4-2022-42rhyh38",
    "plate": "42 RHYH38",
    "brand": "Nissan",
    "model": "navara SE 4X4",
    "version": "navara SE 4X4 · Rojo",
    "year": 2022,
    "price": 135598,
    "listPrice": 15990000,
    "km": 120000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": false,
    "supplier": "RG Motors",
    "techReview": "Al día",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x2-2024-thzg51",
    "plate": "THZG51",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X2",
    "version": "L200 KATANA 4X2 · Rojo",
    "year": 2024,
    "price": 11990000,
    "km": 94407,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "En preparación",
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x4-2020-pgbv11",
    "plate": "PGBV 11",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X4",
    "version": "L200 KATANA 4X4 · Rojo",
    "year": 2020,
    "price": 11990000,
    "km": 129304,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/pgbv11/0.jpg",
    "gallery": [
      "/cars/inventory/pgbv11/0.jpg",
      "/cars/inventory/pgbv11/1.jpg",
      "/cars/inventory/pgbv11/2.jpg",
      "/cars/inventory/pgbv11/3.jpg",
      "/cars/inventory/pgbv11/4.jpg",
      "/cars/inventory/pgbv11/5.jpg",
      "/cars/inventory/pgbv11/6.jpg",
      "/cars/inventory/pgbv11/7.jpg",
      "/cars/inventory/pgbv11/8.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "En preparación",
    "hasRealPhotos": true,
    "supplier": "RQ RUDY CON IVA",
    "techReview": "VENCIDO",
    "circPermit": "marzo 2027",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mitsubishi-new-katana-4x4-2021-pkgf78",
    "plate": "PKGF 78",
    "brand": "Mitsubishi",
    "model": "NEW KATANA 4X4",
    "version": "NEW KATANA 4X4 · Rojo",
    "year": 2021,
    "price": 11990000,
    "km": 203454,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "En preparación",
    "hasRealPhotos": false,
    "supplier": "ECONO CESION RG",
    "techReview": "NOVIEMBRE",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "toyota-hilux-4x4-2022-rzvl18",
    "plate": "RZVL 18",
    "brand": "Toyota",
    "model": "HILUX 4X4",
    "version": "HILUX 4X4 · Rojo",
    "year": 2022,
    "price": 11990000,
    "km": 127576,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "En preparación",
    "hasRealPhotos": false,
    "supplier": "CHARRIOT",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x2-2024-thlv62",
    "plate": "THLV 62",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X2",
    "version": "L200 KATANA 4X2 · Rojo",
    "year": 2024,
    "price": 11990000,
    "km": 69749,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "En preparación",
    "hasRealPhotos": false,
    "supplier": "ECONO CESION RG",
    "techReview": "CARDONAL",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "jac-x200-2022-rzwv49",
    "plate": "RZWV 49",
    "brand": "JAC",
    "model": "X200",
    "version": "X200 · Blanco",
    "year": 2022,
    "price": 11990000,
    "km": 120000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camión",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/rzwv49/0.jpg",
    "gallery": [
      "/cars/inventory/rzwv49/0.jpg",
      "/cars/inventory/rzwv49/1.jpg",
      "/cars/inventory/rzwv49/2.jpg",
      "/cars/inventory/rzwv49/3.jpg",
      "/cars/inventory/rzwv49/4.jpg",
      "/cars/inventory/rzwv49/5.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "En preparación",
    "hasRealPhotos": true,
    "supplier": "CARDONAL",
    "techReview": "Al día",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "toyota-hilux-sr-2023-swzj94",
    "plate": "SWZJ 94",
    "brand": "Toyota",
    "model": "HILUX SR",
    "version": "HILUX SR · Rojo",
    "year": 2023,
    "price": 11990000,
    "km": 120000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "En preparación",
    "hasRealPhotos": false,
    "supplier": "CARDONAL",
    "techReview": "Al día",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mitsubishi-montero-sport-mt-2010-crbw65",
    "plate": "CRBW 65",
    "brand": "Mitsubishi",
    "model": "MONTERO SPORT MT",
    "version": "MONTERO SPORT MT · Blanco",
    "year": 2010,
    "price": 11990000,
    "km": 120000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 5,
    "owners": 1,
    "featured": false,
    "status": "En preparación",
    "hasRealPhotos": false,
    "supplier": "agosto 2026",
    "techReview": "AGOSTO",
    "circPermit": "CARDONAL",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mitsubishi-new-katana-crt-4x2-2019-kwrc91",
    "plate": "KWRC 91",
    "brand": "Mitsubishi",
    "model": "NEW KATANA CRT 4X2",
    "version": "NEW KATANA CRT 4X2 · Rojo",
    "year": 2019,
    "price": 9990000,
    "listPrice": 10990000,
    "km": 389144,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/kwrc91/0.jpg",
    "gallery": [
      "/cars/inventory/kwrc91/0.jpg",
      "/cars/inventory/kwrc91/1.jpg",
      "/cars/inventory/kwrc91/2.jpg",
      "/cars/inventory/kwrc91/3.jpg",
      "/cars/inventory/kwrc91/4.jpg",
      "/cars/inventory/kwrc91/5.jpg",
      "/cars/inventory/kwrc91/6.jpg",
      "/cars/inventory/kwrc91/7.jpg",
      "/cars/inventory/kwrc91/8.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RUDY",
    "techReview": "abril 2027",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "nissan-terrano-4x2-2012-dxtz99",
    "plate": "DXTZ 99",
    "brand": "Nissan",
    "model": "TERRANO 4X2",
    "version": "TERRANO 4X2 · Blanco",
    "year": 2012,
    "price": 4990000,
    "listPrice": 5990000,
    "km": 246800,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Salgado",
    "image": "/cars/inventory/dxtz99/0.jpg",
    "gallery": [
      "/cars/inventory/dxtz99/0.jpg",
      "/cars/inventory/dxtz99/1.jpg",
      "/cars/inventory/dxtz99/2.jpg",
      "/cars/inventory/dxtz99/3.jpg",
      "/cars/inventory/dxtz99/4.jpg",
      "/cars/inventory/dxtz99/5.jpg",
      "/cars/inventory/dxtz99/6.jpg",
      "/cars/inventory/dxtz99/7.jpg",
      "/cars/inventory/dxtz99/8.jpg",
      "/cars/inventory/dxtz99/9.jpg",
      "/cars/inventory/dxtz99/10.jpg",
      "/cars/inventory/dxtz99/11.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "C.PODER",
    "techReview": "enero 2027",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "mg-zs-1-5-2022-rtzh73",
    "plate": "RTZH 73",
    "brand": "MG",
    "model": "ZS 1.5",
    "version": "ZS 1.5 · Rojo",
    "year": 2022,
    "price": 6990000,
    "listPrice": 8490000,
    "km": 106000,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Salgado",
    "image": "/cars/inventory/rtzh73/0.jpg",
    "gallery": [
      "/cars/inventory/rtzh73/0.jpg",
      "/cars/inventory/rtzh73/1.jpg",
      "/cars/inventory/rtzh73/2.jpg",
      "/cars/inventory/rtzh73/3.jpg",
      "/cars/inventory/rtzh73/4.jpg",
      "/cars/inventory/rtzh73/5.jpg",
      "/cars/inventory/rtzh73/6.jpg",
      "/cars/inventory/rtzh73/7.jpg",
      "/cars/inventory/rtzh73/8.jpg",
      "/cars/inventory/rtzh73/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 5,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "C.PODER",
    "techReview": "JUNIO",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "chevrolet-tracker-1-2t-2022-ryyx50",
    "plate": "RYYX50",
    "brand": "Chevrolet",
    "model": "TRACKER 1.2T",
    "version": "TRACKER 1.2T · Azul oscuro",
    "year": 2022,
    "price": 9990000,
    "listPrice": 10990000,
    "km": 49273,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "1.2L Dual VVT-i",
    "power": "87 HP",
    "traction": "4x2",
    "doors": 5,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": false,
    "supplier": "C.PODER",
    "techReview": "SALGADO",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "peugeot-partner-2022-svfd42",
    "plate": "SVFD 42",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2022,
    "price": 10490000,
    "listPrice": 11490000,
    "km": 80438,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/svfd42/0.jpg",
    "gallery": [
      "/cars/inventory/svfd42/0.jpg",
      "/cars/inventory/svfd42/1.jpg",
      "/cars/inventory/svfd42/2.jpg",
      "/cars/inventory/svfd42/3.jpg",
      "/cars/inventory/svfd42/4.jpg",
      "/cars/inventory/svfd42/5.jpg",
      "/cars/inventory/svfd42/6.jpg",
      "/cars/inventory/svfd42/7.jpg",
      "/cars/inventory/svfd42/8.jpg",
      "/cars/inventory/svfd42/9.jpg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "ECONO CESION",
    "techReview": "SALGADO",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "omoda-c5-1-5-aut-2025-vblv57",
    "plate": "VBLV57",
    "brand": "Omoda",
    "model": "C5 1.5 AUT",
    "version": "C5 1.5 AUT · Gris plata",
    "year": 2025,
    "price": 9990000,
    "listPrice": 10990000,
    "km": 32000,
    "fuel": "Bencina",
    "transmission": "Automática",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/vblv57/0.jpg",
    "gallery": [
      "/cars/inventory/vblv57/0.jpg",
      "/cars/inventory/vblv57/1.jpg",
      "/cars/inventory/vblv57/2.jpg",
      "/cars/inventory/vblv57/3.jpg",
      "/cars/inventory/vblv57/4.jpg",
      "/cars/inventory/vblv57/5.jpg",
      "/cars/inventory/vblv57/6.jpg",
      "/cars/inventory/vblv57/7.jpg",
      "/cars/inventory/vblv57/8.jpg",
      "/cars/inventory/vblv57/9.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 5,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "C.PODER",
    "techReview": "SALGADO",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "changan-alsvin-1-4-2021-plxf40",
    "plate": "PLXF40",
    "brand": "Changan",
    "model": "ALSVIN 1.4",
    "version": "ALSVIN 1.4 · Plateado",
    "year": 2021,
    "price": 155519,
    "km": 120000,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Sedán",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/plxf40/0.jpg",
    "gallery": [
      "/cars/inventory/plxf40/0.jpg",
      "/cars/inventory/plxf40/1.jpg",
      "/cars/inventory/plxf40/2.jpg",
      "/cars/inventory/plxf40/3.jpg",
      "/cars/inventory/plxf40/4.jpg",
      "/cars/inventory/plxf40/5.jpg"
    ],
    "engine": "2.4L Turbo",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RG Motors",
    "techReview": "Al día",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "peugeot-partner-l1-blue-hdi-100-1-5-2023-ssdy34",
    "plate": "SSDY34",
    "brand": "Peugeot",
    "model": "PARTNER L1 BLUE HDI 100 1.5",
    "version": "PARTNER L1 BLUE HDI 100 1.5 · Blanco",
    "year": 2023,
    "price": 11990000,
    "km": 73000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Sucursal Salgado",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "1.6L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 3,
    "owners": 1,
    "featured": false,
    "status": "En preparación",
    "hasRealPhotos": false,
    "supplier": "ECONO CESION",
    "techReview": "julio 2027",
    "circPermit": "AGOSTO",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "chevrolet-tahoe-lt-4wd-5-3-2017-jyfw75",
    "plate": "JYFW75",
    "brand": "Chevrolet",
    "model": "TAHOE LT 4WD 5.3",
    "version": "TAHOE LT 4WD 5.3 · Celeste",
    "year": 2017,
    "price": 11990000,
    "km": 120000,
    "fuel": "Bencina",
    "transmission": "Automática",
    "bodyType": "SUV",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/images/placeholder-car.svg",
    "gallery": [
      "/images/placeholder-car.svg"
    ],
    "engine": "3.5L EcoBoost Twin-Turbo V6",
    "power": "450 HP",
    "traction": "4x4",
    "doors": 5,
    "owners": 1,
    "featured": false,
    "status": "Disponible",
    "hasRealPhotos": false,
    "supplier": "RG Motors",
    "techReview": "Al día",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "ford-raptor-f150-2025-tskl58",
    "plate": "TSKL 58",
    "brand": "Ford",
    "model": "RAPTOR F150",
    "version": "RAPTOR F150 · Negra",
    "year": 2025,
    "price": 69990000,
    "km": 10000,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/tskl58/0.jpg",
    "gallery": [
      "/cars/inventory/tskl58/0.jpg",
      "/cars/inventory/tskl58/1.jpg",
      "/cars/inventory/tskl58/2.jpg",
      "/cars/inventory/tskl58/3.jpg",
      "/cars/inventory/tskl58/4.jpg",
      "/cars/inventory/tskl58/5.jpg",
      "/cars/inventory/tskl58/6.jpg",
      "/cars/inventory/tskl58/7.jpg"
    ],
    "engine": "3.5L EcoBoost Twin-Turbo V6",
    "power": "450 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RUDELL",
    "techReview": "EN PODER DE DON RUDY",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  },
  {
    "slug": "ford-raptor-f150-2022-rxzt82",
    "plate": "RXZT 82",
    "brand": "Ford",
    "model": "RAPTOR F150",
    "version": "RAPTOR F150 · Blanca",
    "year": 2022,
    "price": 59990000,
    "km": 82638,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Pickup",
    "location": "Puerto Montt · Sucursal Cardonal",
    "image": "/cars/inventory/rxzt82/0.jpg",
    "gallery": [
      "/cars/inventory/rxzt82/0.jpg",
      "/cars/inventory/rxzt82/1.jpg",
      "/cars/inventory/rxzt82/2.jpg",
      "/cars/inventory/rxzt82/3.jpg",
      "/cars/inventory/rxzt82/4.jpg",
      "/cars/inventory/rxzt82/5.jpg",
      "/cars/inventory/rxzt82/6.jpg",
      "/cars/inventory/rxzt82/7.jpg"
    ],
    "engine": "3.5L EcoBoost Twin-Turbo V6",
    "power": "450 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "status": "Disponible",
    "hasRealPhotos": true,
    "supplier": "RUDY",
    "techReview": "EN PODER DE DON RUDY",
    "circPermit": "Al día",
    "highlights": [
      "Inspección mecánica rigurosa aprobada",
      "Documentación y transferencia inmediata",
      "Garantía técnica de 6 meses",
      "Financiamiento automotriz disponible"
    ]
  }
];

export const vehicles = initialVehicles;

export function getVehicle(slug: string): Vehicle | undefined {
  return vehicles.find((v) => v.slug === slug);
}

export function formatCLP(amount: number): string {
  return new Intl.NumberFormat("es-CL", {
    style: "currency",
    currency: "CLP",
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatKm(km: number): string {
  return new Intl.NumberFormat("es-CL").format(km) + " km";
}

export function estimateMonthly(price: number, termMonths = 48, piePercent = 0.2): number {
  const financed = price * (1 - piePercent);
  const monthlyRate = 0.0129; // ~1.29% mensual
  const factor = (monthlyRate * Math.pow(1 + monthlyRate, termMonths)) / (Math.pow(1 + monthlyRate, termMonths) - 1);
  return Math.round(financed * factor);
}

export function spinFramesOf(v: Vehicle): string[] {
  if (!v.spin || v.spin.count <= 0) return [];
  const { count, pattern = "" } = v.spin;
  return Array.from({ length: count }, (_, i) =>
    pattern ? pattern.replace("{index}", String(i + 1).padStart(3, "0")) : ""
  ).filter(Boolean);
}

export function specsOf(v: Vehicle): { label: string; value: string }[] {
  return [
    { label: "Kilometraje", value: `${v.km.toLocaleString("es-CL")} km` },
    { label: "Año", value: String(v.year) },
    { label: "Combustible", value: v.fuel },
    { label: "Transmisión", value: v.transmission },
    { label: "Potencia", value: v.power },
    { label: "Dueños", value: String(v.owners) },
    { label: "Puertas", value: String(v.doors) },
    { label: "Ubicación", value: v.location },
  ];
}

export const BRANDS = [
  "Toyota",
  "Mitsubishi",
  "Chevrolet",
  "Nissan",
  "Great Wall",
  "Peugeot",
  "Fiat",
  "Hyundai",
  "Subaru",
  "Renault",
  "DFSK",
  "Mercedes-Benz",
  "Ford",
  "Volkswagen",
  "Kia",
  "Suzuki",
  "Otro",
];

export const BODY_TYPES = [
  "Pickup",
  "SUV",
  "Furgón",
  "Sedán",
  "Hatchback",
  "Station Wagon",
  "Otro",
];

export const FUELS = ["Diésel", "Bencina", "Híbrido", "Eléctrico"];

export const TRANSMISSIONS = ["Automática", "Manual"];

export const STATUS_TYPES = ["Disponible", "En reserva", "Vendido", "Borrador", "En preparación"] as const;
